### ISSUE TITLE
背景故事翻译似乎出了问题

### ISSUE THREAD

**Issue by xixikudo** [Ludeon/RimWorld-ChineseSimplified#117]
翻译报告见附件
[TranslationReport.txt](https://github.com/Ludeon/RimWorld-ChineseSimplified/files/4270204/TranslationReport.txt)

**Comment by duduluu** [comment]
这是游戏的bug，贴吧说过了，把 `ChineseSimplified (简体中文).tar` 解压到 `ChineseSimplified` 文件夹，语言切换到这个新文件夹
