### ISSUE TITLE
有兴趣参与汉化可以加QQ群 584053597 ^_^

### ISSUE THREAD

**Issue by duduluu** [Ludeon/RimWorld-ChineseSimplified#18]
@cainiaowu

**Comment by cainiaowu** [comment]
看了下，机器翻译和翻译腔问题挺多的。
专用名词表能否发一份在github wiki里。
QQ什么的平时很少用。

**Comment by zichenzheng** [comment]
能不能建一个Slack感觉会更方便

**Comment by duduluu** [comment]
Slack？没用过……

**Comment by sunnylimail** [comment]
错误报告不见了，还是发群里吧……

**Comment by sunnylimail** [comment]
看起来错误报告贴又被关闭了2018-1-25

**Comment by duduluu** [comment]
@zorbathut 有兴趣参与汉化的话可以加群

**Comment by lonelytb** [comment]
请问下最新版是有其他 fork 吗？发现目前的翻译有一些格式的瑕疵和内容的缺失，但是这里好像只有 B18 的文本，没办法提交修改的版本。加群似乎也没通过验证。

**Comment by Anthony-cto** [comment]
我觉得游戏名字“环世界”的翻译更好些，为什么你一口咬定别人是错的呢？

**Comment by WNJStudio** [comment]
@duduluu 大哥还有打算维护这个repo不？要不给我加点权限，偶尔看看？

**Comment by duduluu** [comment]
@WNJStudio 你直接发PR就行
