### ISSUE TITLE
翻译小BUG反馈

### ISSUE THREAD

**Issue by KagamigawaMeguri** [Ludeon/RimWorld-ChineseSimplified#206]
1.
https://github.com/Ludeon/RimWorld-ChineseSimplified/blob/881b0c1586cea187e73ab09e211641491a092335/Core/Backstories/Backstories.xml#L3342
但大多数时候[都是用 多了个[

2.
https://github.com/Ludeon/RimWorld-ChineseSimplified/blob/881b0c1586cea187e73ab09e211641491a092335/Core/Keyed/Misc_Gameplay.xml#L444
游戏中表达是：
发送某某某，将返回XX天
建议更改类似结构：
发送某某，将于XX天返回
发送某某，返回时间：XX天

**Comment by KagamigawaMeguri** [comment]
还有就是README的安装方法 似乎不太行。
经尝试在以下两个文件夹
RimWorld\Data\Core\Languages\
RimWorld\Data\Royalty\Languages\
或打包成tar 或直接分别放入文件夹手动选择语言。皆可
望更新

**Comment by picasso250** [comment]
所提的两个问题似乎已经修改
