### ISSUE TITLE
出现错误在1.2.3005版本上

### ISSUE THREAD

**Issue by Hxppdv** [Ludeon/RimWorld-ChineseSimplified#256]
官方貌似同步了最新的简中翻译到1.2.3005版本上，导致翻译异常，我能注意到的就有
1.2.3005版本上本应该是Restrict.label，而自带的简中翻译里面则是Schedule.label，这导致了工具栏的翻译失效
而隔壁的繁中翻译则没有这个问题，同时我升级到测试版以后也没有这个问题了。

**Comment by VaniatD** [comment]
这个我们也没办法
