### ISSUE TITLE
翻译缺失

### ISSUE THREAD

**Issue by debugzxcv** [Ludeon/RimWorld-ChineseSimplified#73]
![screenshot5](https://cloud.githubusercontent.com/assets/5125392/26355017/b0d250b4-3ff9-11e7-84ff-ea680a47b279.png)
![screenshot6](https://cloud.githubusercontent.com/assets/5125392/26355019/b1033918-3ff9-11e7-9be4-55f57efa5cdb.png)
![screenshot7](https://cloud.githubusercontent.com/assets/5125392/26355018/b0fdbbbe-3ff9-11e7-9eae-30e806be6d25.png)
![screenshot8](https://cloud.githubusercontent.com/assets/5125392/26355020/b12b7810-3ff9-11e7-9877-cc57754c99b0.png)

**Comment by duduluu** [comment]
感谢，bug已反馈给官方。

**Comment by duduluu** [comment]
已修复，感谢反馈。
