### ISSUE TITLE
error report for FC

### ISSUE THREAD

**Issue by sunnylimail** [Ludeon/RimWorld-ChineseSimplified#78]
hello everyone～

**Comment by duduluu** [comment]
FC是什么意思

**Comment by sunnylimail** [comment]
飞行棺材的缩写

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32412936-b285b65c-c240-11e7-9644-ff97e61e0c4b.jpg)
这个人物背景有点问题，是否应该是中等世界，而非中世纪？
中世纪感觉像欧洲古代那时候……

**Comment by WNJStudio** [comment]
原文Midworld，确实不是中世纪（Medieval）

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32438987-abe7adf4-c327-11e7-95c3-2c8a4a234a63.jpg)
这个缺了一个“自”字，貌似科研列表都却自身的“自”

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32442755-7c02d73e-c337-11e7-856a-386bdecc13fe.jpg)
这里的函数引用有点问题？

**Comment by WNJStudio** [comment]
@sunnylimail 中世纪和科技树问题已提交修正，电路迟点检查下可能是全角半角问题，不过应该不是

**Comment by duduluu** [comment]
OK，晚上修正

**Comment by duduluu** [comment]
@WNJStudio 你的提交不符合规范

**Comment by WNJStudio** [comment]
@duduluu 哦哦，规范是咋样的，哪里看？

**Comment by duduluu** [comment]
@WNJStudio 你看我的commit命名方式，这次我晚上改吧

**Comment by duduluu** [comment]
已修复

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32532811-c60915c2-c487-11e7-9d6f-62e3196fea52.jpg)
战斗记录肢体缺失（肢体损坏）这里还是英文

**Comment by sunnylimail** [comment]
感染致死也是英文

图传不上来，不知道是哪里有问题

**Comment by sunnylimail** [comment]
懂动能是啥？

**Comment by sunnylimail** [comment]
![2](https://user-images.githubusercontent.com/33367015/32559063-3c25e498-c4e1-11e7-90d0-e5db9abbb099.jpg)
![default](https://user-images.githubusercontent.com/33367015/32559237-a736a330-c4e1-11e7-9639-2793ae525694.jpg)
![3](https://user-images.githubusercontent.com/33367015/32559252-af8ff1d0-c4e1-11e7-9d3d-08ce0e8e80a9.jpg)
一块传试试会不会限制

**Comment by WNJStudio** [comment]
@sunnylimail @duduluu 战斗记录已解决，在Core的HediffDef里加了条代表名词的标签 labelNoun，已提交修改，不过看源文件 label 和 labelNoun 是有区别的（因为是名词？）
例：
<label>shut down</label>
<labelNoun>a shutdown command</labelNoun>
那是不是应该翻译为：label 关机，labelNoun 一道关机指令
或者其他的是不是应该为：一只仿生眼，一个缺失的身体部件，一场宿醉之类的？

**Comment by WNJStudio** [comment]
@sunnylimail 脉镜电池问题在哪？轨道轰炸靶向器改了，最后那个不是翻译错误，抚慰性（性质） 心灵立场

**Comment by duduluu** [comment]
@WNJStudio 
战斗记录在哪？你的PR里没有。
HediffDef 里的 labelNoun 是出现在哪里的？
脉京电池没问题。

**Comment by sunnylimail** [comment]
电池那个没看英文原文，误会了。
我当是“闪耀世界科技”的意思，其实是闪耀科技社会的技术等级的意思。

**Comment by sunnylimail** [comment]
那个是立场……力场的问题，field英文里原来就是场，怎么翻译大概都不算错吧。

**Comment by sunnylimail** [comment]
今日更新，新增一个控制按钮
![default](https://user-images.githubusercontent.com/33367015/32604649-526a2392-c589-11e7-9a52-61eadcd1e1d0.jpg)

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32608265-c474caa2-c596-11e7-9af6-c6979e51d26e.jpg)

**Comment by WNJStudio** [comment]
@duduluu Core/Defs/HediffDefs 以及 Core/Defs/Drugs
例Hediffs_Local_Injuries.xml
`<HediffDef>`
    `<hediffClass>Hediff_MissingPart</hediffClass>`
    `<defName>MissingBodyPart</defName>`
    `<label>missing body part</label>`
    `<labelNoun>a missing body part</labelNoun><========================这里`
    `<defaultLabelColor>(0.5, 0.5, 0.5, 1)</defaultLabelColor>`
    `<tendable>true</tendable>`
    `<injuryProps>`
      `<bleedRate>0.05</bleedRate>`
      `<painPerSeverity>0.0125</painPerSeverity>`
    `</injuryProps>`
    `<comps>`
      `<li Class="HediffCompProperties_TendDuration" />`
      `<li Class="HediffCompProperties_GetsOld" />`
    `</comps>`
 ` </HediffDef>`

**Comment by duduluu** [comment]
…………………………我当然知道 labelNoun 是 HediffDef 里，我之前是问你这个 labelNoun 用在什么地方，白天歪果仁告诉我了，是用在 RulePackDef 的战斗记录中的。

**Comment by WNJStudio** [comment]
哦哦，RulePackDef里不是经常有CulpritHediff_labelNoun这条么

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32644124-9a2598b0-c61a-11e7-9771-ff3038a7fee5.jpg)
小时？消失？

**Comment by WNJStudio** [comment]
#84 已提交 @sunnylimail

**Comment by sunnylimail** [comment]
远程武器近战属性这块点开还有英文，还有新建世界地图地名依然是大方块

**Comment by WNJStudio** [comment]
远程武器找不到要改哪个文件😭
地图地名好像是因为用了字体文件（用英文字母的语言都能显示，但是日语韩语中文这种特殊文字就显示方块/乱码）这只能等开发组给个接口了
@sunnylimail @duduluu

**Comment by duduluu** [comment]
@WNJStudio 别找了，这两个bug我都反馈给官方了。
近战每秒伤害里的英文缺少Keyed。
地图地理名称只能显示方块，是因为Unity不支持曲面上直接渲染字体，需要在编译时将字体转换成贴图，中文字库转换成贴图体积爆炸，开发组只将英文字体转换了贴图。
开发组正在研究能在运行时只转换所需文字的方法。

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32842019-fab8646a-ca56-11e7-813c-5a43da235965.jpg)

**Comment by WNJStudio** [comment]
@sunnylimail 是新加的两个精神状态，catatonic和runwild，都会出现这种状况

**Comment by WNJStudio** [comment]
@sunnylimail @duduluu 解决

**Comment by sunnylimail** [comment]
@WNJStudio runwild=回归野性？精神退化？

catatonic
adj. （患） 紧张症的， （患）强直性昏厥的;   
百度翻译

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/32896528-3688ed12-cb1e-11e7-8f78-7a8f6feb5d77.jpg)
错字

**Comment by Wilseanhsu** [comment]
這裡好像很熱鬧阿（滑稽）

可能有人不知道我，我是繁中翻譯的。剛翻到vanometric power cell，來看看簡中怎麼翻...我覺得這值得討論一下。

vano應該不是來自意語，雖然Google也想騙我是意語，但我認為應該是拉丁文(字根)「沒有根據」的意思，我想作者想表達的是無中生有的意思吧。至於和galvanometric有無關聯我就不知了。

另外我看來敘述部份的翻譯有點誤會：
「beyond even most glitterworld societies」這句，我的解讀是「（此科技）甚至超越最閃耀世界的社會」，修飾過後變成「（技術）甚至超越最先進的閃耀世界」。
作者應該是藉此表達遠古人類或是機器和AI遠超人類的能力吧，我強烈懷疑作者也玩過地平線...。

**Comment by WNJStudio** [comment]
@sunnylimail 背景故事我就暂时不动了， @duduluu 在大改ING

**Comment by WNJStudio** [comment]
@Wilseanhsu https://zh.wiktionary.org/wiki/vanum

**Comment by duduluu** [comment]
嗯……“虚空”挺不错的

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/33228462-46d43ec6-d1f7-11e7-868f-226815044e1e.jpg)
这个人物背景翻译缺失

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/33229171-718defec-d204-11e7-888a-0079a6edf7c6.jpg)

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/33240525-00ceb0e0-d2f2-11e7-88e8-9a11fe3894ad.jpg)

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/33481038-c3d93112-d6cd-11e7-8264-aaac6630dc0e.jpg)
@duduluu

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/33941208-b4dc9504-e04c-11e7-9a10-4df6823b831e.jpg)

@duduluu

**Comment by duduluu** [comment]
我草，原来我十几年一只念错这个词

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/33995863-3fe752ba-e11a-11e7-8f2d-aacb714aab20.jpg)
@duduluu

**Comment by duduluu** [comment]
贴张图
![screenshot](https://user-images.githubusercontent.com/10762097/34319476-7777b3b8-e81e-11e7-8962-937123114291.png)

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/35026790-ef37bacc-fb44-11e7-867e-f0f7a2ea33a1.jpg)

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/35217477-5bb51be6-ff63-11e7-92e5-e5e112d31026.jpg)

**Comment by duduluu** [comment]
这自动关闭有点傻逼

**Comment by sunnylimail** [comment]
真是诡异……

**Comment by sunnylimail** [comment]
但是它昂贵的炮管需要频繁的更换维护

**Comment by sunnylimail** [comment]
但是它昂贵的炮管需要频繁的更换维护
![11](https://user-images.githubusercontent.com/33367015/41908332-1f462408-7933-11e8-900d-4458208cc4ee.jpg)

**Comment by sunnylimail** [comment]
![default](https://user-images.githubusercontent.com/33367015/42014469-0e40eeda-7a92-11e8-9692-a683276a2f96.jpg)

**Comment by WNJStudio** [comment]
@duduluu Hi D哥，好久不见，我在想参与参与新DLC的汉化，但是不知道是直接在主Repo还是一个新Repo
PS：如果有需要1.1更新我也可以搭把手

**Comment by duduluu** [comment]
@WNJStudio 游戏内置的导出工具能提取，Tynan这边的说法是要和Core的翻译项目分开，他们那边还有些准备工作，等他通知。你可以加QQ群

**Comment by Wilseanhsu** [comment]
Hi 好久不見，浮上來打個招呼，不然怕被當作作古了哈哈。

**Comment by gaogzs** [comment]
鉴于时间过久，决定关闭该问题，若有其它建议请另开新楼
